version: "3"

services:
    db: 
        container_name: laravel-db
        image: mysql:5.7
        networks:
            - laravel-net
        volumes:
            - laravel-db:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
            - TZ=Asia/Tokyo
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

    app:
        container_name: laravel-app
        depends_on: 
            - db
        build: .
        networks:
            - laravel-net
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www/app/laravel
            - ./logs:/var/www/app/logs
        tty: true

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        networks:
            - laravel-net
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - db
        ports:
            - 8081:80

networks: 
    laravel-net:
volumes:
    laravel-db:
